iris/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("iris_predict_app.urls", namespace="iris_predict_app")),
]

iris_predict_app/urls.py
"""Defines URL patterns for iris_predict_app."""

from django.urls import path
from . import views

app_name = "iris_predict_app"

urlpatterns = [
    path("", views.predict, name="predict"),
    path("iris_predict_app/", views.predict_chances, name="submit_prediction"),
    path('iris_predict_app/train', views.train_model, name="train_model"),
    path('train/', views.train_page, name='train'),
    path('results/', views.view_results, name='results'),
]

iris_predict_app/models.py
from django.db import models


class PredResults(models.Model):
    """A data model to store the input and results."""
    previous_day_pool_price = models.FloatField()
    mean_temp = models.FloatField()
    rolling_30day_avg = models.FloatField()
    alberta_internal_load = models.FloatField()
    ng_price = models.FloatField()
    spd_of_max_gust = models.FloatField()
    day_of_year = models.FloatField()
    total_precip = models.FloatField()
    is_public_holiday = models.FloatField()
    pool_price = models.FloatField()

    class Meta:
        """Tells Django how to use plural names of Pred Results."""
        verbose_name_plural = 'Pred results'

    def __str__(self):
        return self.classification

iris_predict_app/views.py
from django.shortcuts import render
from django.http import JsonResponse
from .models import PredResults
import os
from model.train import load_pickle, train

def predict(request):
    """Show the form to predict."""
    return render(request, "predict.html")

def train_model(request):
    """Make a prediction using the input features from the user."""
    if request.POST.get('action') == 'post':
        # Receive data from client
        start_year = int(request.POST.get('start_year'))
        end_year = int(request.POST.get('end_year'))

        current_path = os.path.dirname(__file__)
        pickle_file_name = os.path.join(current_path, '../', 'ml_models', 'new_model.pickle')
        retcode = train(start_year, end_year, pickle_file_name)

        return JsonResponse({'result': retcode}, safe=False)

def train_page(request):
    return render(request, "train.html")

def predict_chances(request):
    """Make a prediction using the input features from the user."""
    if request.POST.get('action') == 'post':

        # Receive data from client
        previous_day_pool_price = float(request.POST.get('previous_day_pool_price'))
        mean_temp = float(request.POST.get('mean_temp'))
        rolling_30day_avg = float(request.POST.get('rolling_30day_avg'))
        alberta_internal_load = float(request.POST.get('alberta_internal_load'))
        ng_price = float(request.POST.get('ng_price'))
        spd_of_max_gust = float(request.POST.get('spd_of_max_gust'))
        day_of_year = float(request.POST.get('day_of_year'))
        total_precip = float(request.POST.get('total_precip'))
        is_public_holiday = float(request.POST.get('is_public_holiday'))

        # get the file path
        current_path = os.path.dirname(__file__)
        pickle_file_name = os.path.join(current_path, '../', 'ml_models', 'new_model.pickle')

        # Unpickle model
        model = load_pickle(pickle_file_name)
        # Make prediction
        result = model.get_model_predictions([[day_of_year, mean_temp, spd_of_max_gust, total_precip,
                                               alberta_internal_load, rolling_30day_avg, previous_day_pool_price,
                                               is_public_holiday, ng_price]])

        pool_price = result[0]

        PredResults.objects.create(previous_day_pool_price=previous_day_pool_price, mean_temp=mean_temp,
                                   rolling_30day_avg=rolling_30day_avg, alberta_internal_load=alberta_internal_load,
                                   ng_price=ng_price, spd_of_max_gust=spd_of_max_gust, day_of_year=day_of_year,
                                   total_precip=total_precip, is_public_holiday=is_public_holiday,
                                   pool_price=pool_price)

        return JsonResponse({'result': pool_price, 'day_of_year': day_of_year, 'mean_temp': mean_temp,
                             'spd_of_max_gust': spd_of_max_gust, 'total_precip': total_precip,
                             'alberta_internal_load': alberta_internal_load, 'rolling_30day_avg': rolling_30day_avg,
                             'previous_day_pool_price': previous_day_pool_price, 'is_public_holiday': is_public_holiday,
                             'ng_price': ng_price}, safe=False)


def view_results(request):
    """Submit prediction and show all results."""
    data = {"dataset": PredResults.objects.all()}
    return render(request, "results.html", data)

iris_predict_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <title>Electricity forecast</title>
    </head>
    <body>

    {% block main %}
    {% endblock %}

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    </body>
</html>

iris_predict_app/templates/predict.html
{% extends "base.html" %}

{% block main %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/results">Results</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="/train">Training</a>
            </li>
        </ul>
    </div>
</nav>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Prediction Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>Prediction Input:</h5>
                <div>Day of Year: <span id="doy"></span></div>
                <div>Previous Day Pool Price: <span id="pdpp"></span></div>
                <div>Natural Gas Price: <span id="ngp"></span></div>
                <div>Mean Temperature: <span id="mt"></span></div>
                <div>Alberta Internal Load: <span id="ail"></span></div>
                <div>Rolling 30 Day Average: <span id="rtda"></span></div>
                <div>Speed of Max Gust: <span id="somg"></span></div>
                <div>Total Precipitation: <span id="tp"></span></div>
                <div>Is Public Holiday: <span id="iph"></span></div>
                <h5 class="pt-3">Pool Price:</h5>
                <div id="prediction"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <a class="btn btn-primary" href="/results/" role="button">View database</a>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-lg-12">
            <h1>Prediction</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-row">
                    <!-- Date information group -->
                    <fieldset class="col-lg-3 border p-2">
                        <legend class="w-auto">Date Information</legend>
                        <div class="form-group mx-2">
                            <label for="day_of_year">Day of Year:</label>
                            <input type="number" step="1" class="form-control" id="day_of_year" placeholder="1" required>
                            <small class="form-text text-muted">Enter the day of the year as a number from 1 to 366. Day 1 is January 1st.</small>
                        </div>
<!--                        <div class="form-group mx-2">-->
<!--                            <label for="is_public_holiday">Is Public Holiday:</label>-->
<!--                            <input type="number" step="1" class="form-control" id="is_public_holiday" placeholder="0">-->
<!--                            <small class="form-text text-muted">Enter 1 for Yes or 0 for No.</small>-->
<!--                        </div>-->
                        <!-- Long: I want to try making the radio button for 
                            this input feature but it returns an error with POST.
                            I'll try again later.-->
                        <div class="form-group mx-2">
                            <label>Is Public Holiday:</label>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="is_public_holiday" id="holiday_yes" value="1">
                                <label class="form-check-label" for="holiday_yes">Yes</label>
                            </div>
                            <div class="form-check">
                                <input class="form-check-input" type="radio" name="is_public_holiday" id="holiday_no" value="0" checked>
                                <label class="form-check-label" for="holiday_no">No</label>
                            </div>
                        </div>
                    </fieldset>

                    <!-- Weather conditions group -->
                    <fieldset class="col-lg-3 border p-2 mx-4">
                        <legend class="w-auto">Weather Conditions</legend>
                        <div class="form-group mx-2">
                            <label for="mean_temp">Mean Temperature (&deg;C):</label>
                            <input type="number" step="0.0000000001" class="form-control" id="mean_temp" placeholder="0.0" required>
                            <small class="form-text text-muted">Enter a number between -30 and 26.</small>
                        </div>
                        <div class="form-group mx-2">
                            <label for="spd_of_max_gust">Speed of Max Gust (km/h):</label>
                            <input type="number" step="0.0000000001" class="form-control" id="spd_of_max_gust" placeholder="0.0" required>
                            <small class="form-text text-muted">Enter a number between 0 and 95.</small>
                        </div>
                        <div class="form-group mx-2">
                            <label for="total_precip">Total Precipitation (mm):</label>
                            <input type="number" step="0.0000000001" class="form-control" id="total_precip" placeholder="0.0" required>
                            <small class="form-text text-muted">Enter a number between 0 and 59.8.</small>
                        </div>
                    </fieldset>
                    
                    <!-- Energy prices group -->
                    <fieldset class="col-lg-3 border p-2">
                        <legend class="w-auto">Energy Prices</legend>
                        <div class="form-group mx-2">
                            <label for="previous_day_pool_price">Previous Day Pool Price ($):</label>
                            <input type="number" step="0.0000000001" class="form-control" id="previous_day_pool_price" placeholder="0.0" required>
                            <small class="form-text text-muted">Enter a number between 0 and 794.</small>
                        </div>
                        <div class="form-group mx-2">
                            <label for="ng_price">Natural Gas Price ($/MCF):</label>
                            <input type="number" step="0.0000000001" class="form-control" id="ng_price" placeholder="0.0" required>
                            <small class="form-text text-muted"></small>
                        </div>
                        <div class="form-group mx-2">
                            <label for="alberta_internal_load">Alberta Internal Load (MW):</label>
                            <input type="number" step="0.0000000001" class="form-control" id="alberta_internal_load" placeholder="0.0" required>
                            <small class="form-text text-muted">Enter a number between 7500 and 12000.</small>
                        </div>
                        <div class="form-group mx-2">
                            <label for="rolling_30day_avg">Rolling 30 Day Average Price ($):</label>
                            <input type="number" step="0.0000000001" class="form-control" id="rolling_30day_avg" placeholder="0.0" required>
                            <small class="form-text text-muted">Enter a number between 14 and 348.</small>
                        </div>
                    </fieldset>
                </div>
                
                <div class="mt-3 text-left">
                    <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "iris_predict_app:submit_prediction" %}',
            data:{
                previous_day_pool_price:$('#previous_day_pool_price').val(),
                mean_temp:$('#mean_temp').val(),
                rolling_30day_avg:$('#rolling_30day_avg').val(),
                alberta_internal_load:$('#alberta_internal_load').val(),
                ng_price:$('#ng_price').val(),
                spd_of_max_gust:$('#spd_of_max_gust').val(),
                day_of_year:$('#day_of_year').val(),
                total_precip:$('#total_precip').val(),
                is_public_holiday:$('input[name=is_public_holiday]').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
                document.getElementById("doy").innerHTML = json['day_of_year']
                document.getElementById("pdpp").innerHTML = json['previous_day_pool_price']
                document.getElementById("ngp").innerHTML = json['ng_price']
                document.getElementById("mt").innerHTML = json['mean_temp']
                document.getElementById("ail").innerHTML = json['alberta_internal_load']
                document.getElementById("rtda").innerHTML = json['rolling_30day_avg']
                document.getElementById("somg").innerHTML = json['spd_of_max_gust']
                document.getElementById("tp").innerHTML = json['total_precip']
                document.getElementById("iph").innerHTML = json['is_public_holiday']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>

{% endblock %}

iris_predict_app/templates/results.html
{% extends "base.html" %}

{% block main %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/results">Results</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/train">Training</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container pt-5">
        <div class="row">
        <h1>Results</h1>
            <table class="table">
                <thead>
                <tr>
                <th scope="col">#</th>
                <th scope="col">Day of Year</th>
                <th scope="col">Previous Day Pool Price</th>
                <th scope="col">Natural Gas Price</th>
                <th scope="col">Mean Temperature</th>
                <th scope="col">Alberta Internal Load</th>
                <th scope="col">Rolling 30 Day Average</th>
                <th scope="col">Speed of Max Gust</th>
                <th scope="col">Total Precipitation</th>
                <th scope="col">Is Public Holiday</th>
                <th scope="col">Pool Price Prediction</th>
                </tr>
                </thead>
                <tbody>

                {% for data in dataset %}
                    <tr>
                    <th scope="row">{{ data.id }}</th>
                    <td>{{ data.day_of_year }}</td>
                    <td>{{ data.previous_day_pool_price }}</td>
                    <td>{{ data.ng_price }}</td>
                    <td>{{ data.mean_temp }}</td>
                    <td>{{ data.alberta_internal_load }}</td>
                    <td>{{ data.rolling_30day_avg }}</td>
                    <td>{{ data.spd_of_max_gust }}</td>
                    <td>{{ data.total_precip }}</td>
                    <td>{{ data.is_public_holiday }}</td>
                    <td>{{ data.pool_price }}</td>
                    </tr>
                {% endfor %}
                
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

iris_predict_app/templates/train.html
{% extends "base.html" %}

{% block main %}
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="/">Prediction <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/results">Results</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="/train">Training</a>
                </li>
            </ul>
        </div>
    </nav>

<!-- Modal -->
<div class="modal fade" id="retrainModal" tabindex="-1" role="dialog" aria-labelledby="retrainModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="retrainModalLabel">Retrain Results</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div>Retraining the Model...</div>
                <div>Model R2 Score: <span id="prediction"></span></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="container pt-5">
    <div class="row justify-content-md-center">
        <div class="col-md-4">
            <h1>Training</h1>
            <form action="" id="post-form">
                {% csrf_token %}
                <div class="form-group">
                    <label for="start_year">Start Year</label>
                    <input type="number" step="1" class="form-control" id="start_year" placeholder="" required>
                </div>
                <div class="form-group">
                    <label for="end_year">End Year</label>
                    <input type="number" step="1" class="form-control" id="end_year" placeholder="" required>
                </div>
                <div class="button-box col-lg-12">
                    <button type="submit" value="Submit" class="btn btn-primary" data-toggle="modal" data-target="#retrainModal">ReTrain</button>
                </div>

            </form>
        </div>
    </div>
</div>

<script>
    $(document).on('submit', '#post-form',function(e){
        e.preventDefault();
        $.ajax({
            type:'POST',
            url:'{% url "iris_predict_app:train_model" %}',
            data:{
                start_year:$('#start_year').val(),
                end_year:$('#end_year').val(),
                csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val(),
                action: 'post'
            },
            success:function(json) {
                document.forms["post-form"].reset();
                document.getElementById("prediction").innerHTML = json['result']
            },
            error : function(xhr,errmsg,err) {

            }
        });
    })
</script>


{% endblock %}